name: Deploy Azure Function App - functions-pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Azure Functions Core Tools
        run: |
          npm install -g azure-functions-core-tools@4 --unsafe-perm true

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D06E03BDC4A94C7E9F4050B6113669D2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_80350A22BBD74C05A5569EA8BB98A4C1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AD2F17CCCC87402595FFA788627D5DE2 }}

      - name: Publish to Azure Functions
        run: |
          func azure functionapp publish functions-pipeline --python --build remote